name: Build and test

on: 
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest # Machine

    steps:
      - name: checkout code
        uses: actions/checkout@v4 # uses -> use some actions script template

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: cache node modules # Use cache avoid install in each jobs
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: install dependencies
        run: npm ci

      - name: run test
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: install dependencies
        run: npm ci

      - name: run build
        run: npm run build
  